// Generated by openapi-typescript. Do not edit.
export type paths = {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/capabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Capabilities */
    get: operations['getWorkerCapabilities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Job */
    post: operations['submitWorkerJob'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations['getWorkerJob'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/jobs/{job_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Job */
    post: operations['cancelWorkerJob'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/jobs/{job_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Job Events */
    get: operations['streamWorkerJobEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/methods': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Methods */
    get: operations['listWorkerMethods'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/shutdown': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Shutdown */
    post: operations['shutdownWorker'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/worker/v1/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Version */
    get: operations['getWorkerVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    /** CleaningParameters */
    CleaningParameters: {
      /** Expectedfields */
      expectedFields?: {
        [key: string]: 'string' | 'int' | 'float' | 'bool' | 'datetime';
      };
      /**
       * Facetlimit
       * @default 10
       */
      facetLimit: number;
      /** Fingerprint */
      fingerprint: string;
      /** Manifestartifactref */
      manifestArtifactRef: string;
      /**
       * Previewlimit
       * @default 10
       */
      previewLimit: number;
      /** Steps */
      steps: (
        | components['schemas']['TrimCleaningStep']
        | components['schemas']['NullCleaningStep']
        | components['schemas']['ConvertCleaningStep']
        | components['schemas']['SplitCleaningStep']
        | components['schemas']['MergeCleaningStep']
        | components['schemas']['DedupeCleaningStep']
      )[];
    };
    /** ConvertCleaningStep */
    ConvertCleaningStep: {
      /** Fields */
      fields: string[];
      /**
       * Onerror
       * @default null
       * @enum {string}
       */
      onError: 'null' | 'fail';
      /**
       * Targettype
       * @enum {string}
       */
      targetType: 'number' | 'date';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'convert';
    };
    /** DedupeCleaningStep */
    DedupeCleaningStep: {
      /** Fields */
      fields: string[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'dedupe';
    };
    /** MergeCleaningStep */
    MergeCleaningStep: {
      /** Fields */
      fields: string[];
      /**
       * Separator
       * @default
       */
      separator: string;
      /** Target */
      target: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'merge';
    };
    /** MethodDescriptor */
    MethodDescriptor: {
      /** Category */
      category: string;
      /** Descriptionkey */
      descriptionKey: string;
      /** Id */
      id: string;
      /**
       * Internal
       * @default false
       */
      internal: boolean;
      /** Outputschema */
      outputSchema: {
        [key: string]: unknown;
      };
      /** Parameterschema */
      parameterSchema: {
        [key: string]: unknown;
      };
      /** Recommendedvisualizations */
      recommendedVisualizations?: string[];
      /** Resourcelimits */
      resourceLimits?: {
        [key: string]: unknown;
      };
      /** Supportedfieldtypes */
      supportedFieldTypes?: string[];
      /**
       * Supportssampling
       * @default false
       */
      supportsSampling: boolean;
      /** Titlekey */
      titleKey: string;
      /** Version */
      version: string;
    };
    /** NullCleaningStep */
    NullCleaningStep: {
      /** Fields */
      fields: string[];
      /** Tokens */
      tokens?: string[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'normalize_null';
    };
    /** Problem */
    Problem: {
      /** Code */
      code: string;
      /** Detail */
      detail: string;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /**
       * Type
       * @default about:blank
       */
      type: string;
    };
    /** SplitCleaningStep */
    SplitCleaningStep: {
      /** Delimiter */
      delimiter: string;
      /** Field */
      field: string;
      /** Targets */
      targets: string[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'split';
    };
    /** TrimCleaningStep */
    TrimCleaningStep: {
      /** Fields */
      fields: string[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'trim';
    };
    /** WorkerCapabilities */
    WorkerCapabilities: {
      /**
       * Arbitrarycodeexecution
       * @default false
       * @constant
       */
      arbitraryCodeExecution: false;
      /**
       * Arbitrarysqlexecution
       * @default false
       * @constant
       */
      arbitrarySqlExecution: false;
      /**
       * Externalnetwork
       * @default false
       * @constant
       */
      externalNetwork: false;
      /**
       * Maxconcurrentjobs
       * @default 1
       * @constant
       */
      maxConcurrentJobs: 1;
      /**
       * Workspaceisolation
       * @default true
       * @constant
       */
      workspaceIsolation: true;
    };
    /** WorkerJob */
    WorkerJob: {
      /** Completedat */
      completedAt?: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      error?: components['schemas']['WorkerJobError'] | null;
      /** Id */
      id: string;
      /** Methodid */
      methodId: string;
      /** Methodversion */
      methodVersion: string;
      /** Outputartifactref */
      outputArtifactRef?: string | null;
      /** Phase */
      phase: string;
      /** Progress */
      progress: number;
      /** Startedat */
      startedAt?: string | null;
      /**
       * State
       * @enum {string}
       */
      state: 'queued' | 'running' | 'canceling' | 'canceled' | 'succeeded' | 'failed';
    };
    /** WorkerJobError */
    WorkerJobError: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /**
       * Retryable
       * @default false
       */
      retryable: boolean;
    };
    /** WorkerJobSubmission */
    WorkerJobSubmission: {
      /** Inputartifactref */
      inputArtifactRef?: string | null;
      /** Jobid */
      jobId: string;
      /** Methodid */
      methodId: string;
      /** Methodversion */
      methodVersion: string;
      /**
       * Outputartifactref
       * @default result.json
       */
      outputArtifactRef: string;
      /** Parameters */
      parameters?:
        | {
            [key: string]: unknown;
          }
        | components['schemas']['CleaningParameters'];
    };
    /** WorkerVersion */
    WorkerVersion: {
      /** Generation */
      generation: number;
      /**
       * Protocolversion
       * @default worker/v1
       * @constant
       */
      protocolVersion: 'worker/v1';
      /** Workerversion */
      workerVersion: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  getWorkerCapabilities: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkerCapabilities'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  submitWorkerJob: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkerJobSubmission'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkerJob'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  getWorkerJob: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkerJob'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  cancelWorkerJob: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkerJob'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  streamWorkerJobEvents: {
    parameters: {
      query?: {
        last_event_id?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  listWorkerMethods: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MethodDescriptor'][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  shutdownWorker: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  getWorkerVersion: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkerVersion'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
}
