import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import { format } from 'prettier';

const documentPath = resolve(
  import.meta.dirname,
  '../../../services/analytics-worker/openapi.json',
);
const target = resolve(import.meta.dirname, '../src/openapi.generated.d.ts');
const document = JSON.parse(await readFile(documentPath, 'utf8')) as never;
const ast = await openapiTS(document, { alphabetize: true, exportType: true });
const output = await format(
  `// Generated by openapi-typescript. Do not edit.\n${astToString(ast)}`,
  {
    parser: 'typescript',
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
  },
);

if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== output) {
    console.error(
      'Worker OpenAPI client types are out of date. Run: bun run worker:client:generate',
    );
    process.exit(1);
  }
} else {
  await writeFile(target, output);
}
